# Generated by Django 4.2.1 on 2023-05-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durata', models.IntegerField()),
                ('pret', models.FloatField()),
                ('descriere', models.TextField()),
                ('nume', models.CharField(max_length=30)),
            ],
        ),
    ]
