# Generated by Django 4.2.1 on 2023-06-05 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0003_alter_curs_descriere'),
    ]

    operations = [
        migrations.AddField(
            model_name='curs',
            name='actualizat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='curs',
            name='creat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
