# Generated by Django 4.2.1 on 2023-06-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0004_curs_actualizat_curs_creat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curs',
            name='pret',
            field=models.FloatField(db_index=True),
        ),
    ]
