# Generated by Django 4.2.1 on 2023-06-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0005_alter_curs_pret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curs',
            name='nume',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
