# Generated by Django 4.2.1 on 2023-06-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0006_alter_curs_nume'),
    ]

    operations = [
        migrations.AddField(
            model_name='curs',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
