# Generated by Django 4.2.1 on 2023-06-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0008_curs_activ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('prenume', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=10)),
            ],
        ),
    ]
