# Generated by Django 4.2.1 on 2023-06-05 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0009_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='curs',
            name='profesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curs.profesor'),
            preserve_default=False,
        ),
    ]
