# Generated by Django 4.2.1 on 2023-06-05 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0010_curs_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='curs',
            name='coordonator',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coordonator', to='curs.profesor'),
            preserve_default=False,
        ),
    ]
