# Generated by Django 4.2.1 on 2023-06-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0012_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='curs',
            name='an',
            field=models.IntegerField(default=1),
        ),
    ]
