# Generated by Django 4.2.1 on 2023-06-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0013_curs_an'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['prenume', 'nume']},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('prenume', 'nume')},
        ),
    ]
