# Generated by Django 4.2.1 on 2023-06-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0014_alter_student_options_alter_student_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='an',
            field=models.IntegerField(default=1),
        ),
    ]
