# Generated by Django 4.2.1 on 2023-06-27 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0016_alter_curs_options_alter_profesor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intrebare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Raspuns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('corect', models.BooleanField(default=False)),
                ('intrebare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curs.intrebare')),
            ],
        ),
    ]
