# Generated by Django 4.2.1 on 2023-06-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0017_intrebare_raspuns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intrebare',
            options={'verbose_name_plural': 'intrebari'},
        ),
        migrations.AlterModelOptions(
            name='raspuns',
            options={'verbose_name_plural': 'raspunsuri'},
        ),
    ]
