# Generated by Django 4.2.1 on 2023-07-10 16:46

from django.db import migrations

def forward(apps, schema):
    print("inainte")
    Curs = apps.get_model("curs", "Curs")
    modificat = Curs.objects.all().update(an=2023)
    print(f"{modificat} randuri modificate")

def backward(apps, schema):
    print("inapoi")
    raise ValueError("Nu pot sa pun valorile vechi inapoi")


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0020_todo_created_todo_last_update'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
