# Generated by Django 4.2.1 on 2023-07-10 17:05

from django.db import migrations


def forward(apps, schema):
    print("inainte")
    Student = apps.get_model("curs", "Student")
    modificat = 0
    for student in Student.objects.all():
        nume_db = student.nume
        nume, prenume = nume_db.split(" ")
        student.nume = nume
        student.prenume = prenume
        student.save()
        modificat += 1
    print(f"{modificat} randuri modificate")

def backward(apps, schema):
    print("inapoi")
    raise ValueError("Nu pot sa pun valorile vechi inapoi")

class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0021_an_2023'),
    ]

    operations = [
        migrations.RunPython(forward, backward)  
    ]
